SUPPORTED_ARTICULATIONS = [
	'SNARE',
	'SNARE_SIDESTICK',
	'SNARE_RIMSHOT',
	'SNARE_FLAM',
	'KICK',
	'TOM1',
	'TOM2',
	'TOM3',
	'TOM4',
	'TOM5',
	'TOM6',
	'HIHAT_CLOSED',
	'HIHAT_PEDAL',
	'HIHAT_OPEN',
	'HIHAT_OPEN_BELL',
	'CRASH1',
	'CRASH2',
	'RIDE_EDGE',
	'RIDE_BOW',
	'RIDE_BELL',
	'CHINA',
	'SPLASH',
	'COWBELL'
]

ARTICULATIONS = {}

for i, name in enumerate(SUPPORTED_ARTICULATIONS):
	ARTICULATIONS[name] = i

ARTICULATIONS["NO_HIT"] = -1
NUM_ARTICULATIONS = len(SUPPORTED_ARTICULATIONS)
